[package]
name = "env-logger"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = { version = "0.11.8", registry = "artifactory" }
log = { version = "0.4.28", registry = "artifactory" }
chrono = { version = "0.4.42", registry = "artifactory" }
