[package]
name = "reqwest-response"
version = "0.1.0"
edition = "2024"
publish = ["artifactory"]

[dependencies]
reqwest = { version = "0.12.24", default-features=false, features=["json"], registry = "artifactory" }
tokio = { version = "1.48.0", features = ["full"], registry = "artifactory" }
