[package]
name = "tcp_file_transfer"
version = "0.1.0"
edition = "2024"
publish = ["artifactory"]

[dependencies]

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"